import { useGenerateInsight, usePaperInsight } from "../api/queries";
import type { PaperInsightResult } from "../api/types";
import { ErrorState, Loading } from "./StateViews";

function Items({ label, items, chips = false }: { label: string; items: string[]; chips?: boolean }) {
  if (items.length === 0) return null;
  return (
    <div>
      <dt>{label}</dt>
      <dd>
        {chips ? (
          <div className="chips">
            {items.map((i) => (
              <span key={i} className="chip">
                {i}
              </span>
            ))}
          </div>
        ) : (
          <ul>
            {items.map((i) => (
              <li key={i}>{i}</li>
            ))}
          </ul>
        )}
      </dd>
    </div>
  );
}

function Result({ data }: { data: PaperInsightResult }) {
  const { insight } = data;
  return (
    <>
      {/* Model output is untrusted: rendered as plain text only. */}
      <p className="insight-summary">{insight.summary}</p>
      <dl className="insight-grid">
        <Items label="Contributions" items={insight.contributions} />
        <Items label="Methods" items={insight.methods} chips />
        <Items label="Tasks" items={insight.tasks} chips />
        <Items label="Datasets" items={insight.datasets} chips />
        <Items label="Limitations stated" items={insight.limitations} />
        <Items label="Keywords" items={insight.keywords} chips />
      </dl>
    </>
  );
}

/** AI summary and structured extraction for a paper, generated on demand and then cached. */
export function InsightCard({ paperId, hasAbstract }: { paperId: string; hasAbstract: boolean }) {
  const query = usePaperInsight(paperId);
  const generate = useGenerateInsight(paperId);
  const data = query.data ?? undefined;

  return (
    <section className="card card-pad" aria-labelledby="insight-heading">
      <h2 id="insight-heading">
        AI summary <span className="chip chip-accent">{data ? data.insight.kind : "AI"}</span>
      </h2>
      {query.isPending && <Loading label="Loading AI summary" />}
      {query.isError && <ErrorState error={query.error} onRetry={() => void query.refetch()} />}
      {data && <Result data={data} />}
      {query.isSuccess && !data && (
        <p className="muted">
          {hasAbstract
            ? "No summary has been generated for this paper yet."
            : "This paper has no abstract, so there is nothing to summarise."}
        </p>
      )}
      {generate.isError && <ErrorState error={generate.error} />}
      {query.isSuccess && hasAbstract && (
        <div className="insight-foot">
          <button
            type="button"
            className={data ? "btn" : "btn btn-primary"}
            disabled={generate.isPending}
            onClick={() => generate.mutate(Boolean(data))}
          >
            {generate.isPending ? "Generating…" : data ? "Regenerate" : "Generate summary"}
          </button>
          {data && (
            <span className="small faint">
              Generated by {data.model}
              {data.stale && " · the abstract has changed since"}. AI output can be wrong; check it
              against the abstract.
            </span>
          )}
        </div>
      )}
    </section>
  );
}
