/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analytics/influential": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Most structurally influential papers or authors (see `note` in the response) */
        get: operations["influential_api_analytics_influential_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_analytics_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_api_analytics_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_analytics_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_analytics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/years": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Number of ingested papers per publication year (stubs excluded) */
        get: operations["papers_per_year_api_analytics_years_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/authors/{author_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Author */
        get: operations["get_author_api_authors__author_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/communities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Communities */
        get: operations["list_communities_api_communities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/communities/{community_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Community */
        get: operations["get_community_api_communities__community_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/neighborhood/{paper_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Citation neighbourhood of a paper, for visualisation */
        get: operations["neighborhood_api_graph_neighborhood__paper_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Most influential papers and the citations among them, for visualisation */
        get: operations["overview_api_graph_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/shortest-path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Shortest undirected path between two nodes over selected relationship types */
        get: operations["shortest_path_api_graph_shortest_path_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe (checks backing services) */
        get: operations["ready_api_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingestion/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent ingestion jobs */
        get: operations["list_jobs_api_ingestion_jobs_get"];
        put?: never;
        /** Create and enqueue an ingestion job */
        post: operations["create_job_api_ingestion_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingestion/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ingestion job status */
        get: operations["get_job_api_ingestion_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingestion/jobs/{job_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-enqueue a failed or interrupted job; it continues from its checkpoint */
        post: operations["resume_job_api_ingestion_jobs__job_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List papers */
        get: operations["list_papers_api_papers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paper details */
        get: operations["get_paper_api_papers__paper_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/citations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Papers citing this paper */
        get: operations["get_citations_api_papers__paper_id__citations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/references": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Papers cited by this paper */
        get: operations["get_references_api_papers__paper_id__references_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/related": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Related papers by Personalized PageRank over the local citation neighbourhood */
        get: operations["related_papers_api_papers__paper_id__related_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Structurally similar papers (bibliographic coupling or co-citation) */
        get: operations["similar_papers_api_papers__paper_id__similar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Keyword search over papers, authors and topics */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Topics */
        get: operations["list_topics_api_topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics/{topic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Topic */
        get: operations["get_topic_api_topics__topic_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyticsRunCreate */
        AnalyticsRunCreate: {
            /** Backend */
            backend?: ("auto" | "gds" | "networkx") | null;
            /**
             * Community Algorithm
             * @default louvain
             * @enum {string}
             */
            community_algorithm: "louvain" | "leiden";
            /**
             * Min Community Size
             * @default 3
             */
            min_community_size: number;
        };
        /** AnalyticsRunOut */
        AnalyticsRunOut: {
            /** Backend */
            backend: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Options */
            options: {
                [key: string]: unknown;
            };
            /** Report */
            report: {
                [key: string]: unknown;
            };
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
        };
        /** AuthorActivity */
        AuthorActivity: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Paper Count */
            paper_count: number;
        };
        /** AuthorDetail */
        AuthorDetail: {
            /** Collaborators */
            collaborators: components["schemas"]["CollaboratorRef"][];
            /** Id */
            id: string;
            /** Institutions */
            institutions: components["schemas"]["InstitutionRef"][];
            metrics: components["schemas"]["GraphMetrics"];
            /** Name */
            name: string;
            /** Openalex Id */
            openalex_id: string | null;
            /** Orcid */
            orcid: string | null;
            /** Papers */
            papers: components["schemas"]["PaperSummary"][];
            /** Topics */
            topics: components["schemas"]["TopicRef"][];
        };
        /** AuthorRef */
        AuthorRef: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Orcid */
            orcid: string | null;
            /** Position */
            position: number | null;
        };
        /** CollaboratorRef */
        CollaboratorRef: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Shared Papers */
            shared_papers: number;
        };
        /** CommunityDetail */
        CommunityDetail: {
            /** Algorithm */
            algorithm: string;
            /** Computed At */
            computed_at: string | null;
            /** Connections */
            connections: components["schemas"]["CommunityLink"][];
            /** Id */
            id: string;
            /** Institutions */
            institutions: components["schemas"]["CountItem"][];
            /** Label */
            label: string | null;
            /** Papers Per Year */
            papers_per_year: {
                [key: string]: number;
            };
            /** Rank */
            rank: number;
            /**
             * Scope
             * @enum {string}
             */
            scope: "papers" | "authors";
            /** Size */
            size: number;
            /** Top Authors */
            top_authors: components["schemas"]["CountItem"][];
            /** Top Papers */
            top_papers: components["schemas"]["PaperSummary"][];
            /** Top Topics */
            top_topics: string[];
            /** Topics */
            topics: components["schemas"]["CountItem"][];
        };
        /** CommunityLink */
        CommunityLink: {
            /** Citations In */
            citations_in: number;
            /** Citations Out */
            citations_out: number;
            /** Community Id */
            community_id: string;
            /** Label */
            label: string | null;
        };
        /** CommunitySummary */
        CommunitySummary: {
            /** Algorithm */
            algorithm: string;
            /** Computed At */
            computed_at: string | null;
            /** Id */
            id: string;
            /** Label */
            label: string | null;
            /** Rank */
            rank: number;
            /**
             * Scope
             * @enum {string}
             */
            scope: "papers" | "authors";
            /** Size */
            size: number;
            /** Top Topics */
            top_topics: string[];
        };
        /** CountItem */
        CountItem: {
            /** Count */
            count: number;
            /** Id */
            id: string | null;
            /** Name */
            name: string;
        };
        /** GraphEdge */
        GraphEdge: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /**
             * Type
             * @default CITES
             */
            type: string;
        };
        /**
         * GraphMetrics
         * @description Structural metrics from graph analytics. ``None`` until analytics have run.
         */
        GraphMetrics: {
            /** Betweenness */
            betweenness: number | null;
            /** Community Id */
            community_id: string | null;
            /** In Degree */
            in_degree: number | null;
            /** Out Degree */
            out_degree: number | null;
            /** Pagerank */
            pagerank: number | null;
        };
        /**
         * GraphNode
         * @description A paper as drawn in the graph view.
         */
        GraphNode: {
            /** Authors */
            authors: string[];
            /**
             * Cited By In Graph
             * @default 0
             */
            cited_by_in_graph: number;
            /** Community Id */
            community_id: string | null;
            /** Community Label */
            community_label: string | null;
            /** Id */
            id: string;
            /**
             * Is Stub
             * @default false
             */
            is_stub: boolean;
            /** Pagerank */
            pagerank: number | null;
            /** Title */
            title: string | null;
            /** Year */
            year: number | null;
        };
        /** GraphSummary */
        GraphSummary: {
            /** Analytics Computed At */
            analytics_computed_at: string | null;
            /** Author Communities */
            author_communities: number;
            /** Authors */
            authors: number;
            /** Citations */
            citations: number;
            /** Institutions */
            institutions: number;
            /** Paper Communities */
            paper_communities: number;
            /** Papers */
            papers: number;
            /** Stub Papers */
            stub_papers: number;
            /** Topics */
            topics: number;
            /** Venues */
            venues: number;
        };
        /**
         * GraphView
         * @description A bounded subgraph for visualisation. Edges point from the citing to the cited paper.
         */
        GraphView: {
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
            /** Focus */
            focus: string | null;
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Note */
            note: string;
            /** Total Papers */
            total_papers: number | null;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InfluentialResponse */
        InfluentialResponse: {
            /** Authors */
            authors: components["schemas"]["RankedAuthor"][];
            /**
             * Entity
             * @enum {string}
             */
            entity: "paper" | "author";
            /** Metric */
            metric: string;
            /** Note */
            note: string;
            /** Papers */
            papers: components["schemas"]["RankedPaper"][];
        };
        /** IngestionJobCreate */
        IngestionJobCreate: {
            params: components["schemas"]["IngestionParams"];
            /**
             * Source
             * @default openalex
             */
            source: string;
        };
        /** IngestionJobOut */
        IngestionJobOut: {
            /** Attempts */
            attempts: number;
            /** Checkpoint */
            checkpoint: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Source */
            source: string;
            /** Started At */
            started_at: string | null;
            /** Stats */
            stats: {
                [key: string]: unknown;
            };
            status: components["schemas"]["JobStatus"];
        };
        /** IngestionParams */
        IngestionParams: {
            /**
             * Hydrate References
             * @default 0
             */
            hydrate_references: number;
            /**
             * Max Results
             * @default 200
             */
            max_results: number;
            /**
             * Per Page
             * @default 50
             */
            per_page: number;
            /** Query */
            query: string;
            /** Year From */
            year_from?: number | null;
            /** Year To */
            year_to?: number | null;
        };
        /** InstitutionRef */
        InstitutionRef: {
            /** Country */
            country: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /** Page[PaperSummary] */
        Page_PaperSummary_: {
            /** Items */
            items: components["schemas"]["PaperSummary"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** Page[TopicListItem] */
        Page_TopicListItem_: {
            /** Items */
            items: components["schemas"]["TopicListItem"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** PaperDetail */
        PaperDetail: {
            /** Abstract */
            abstract: string | null;
            /** Arxiv Id */
            arxiv_id: string | null;
            /** Authors */
            authors: components["schemas"]["AuthorRef"][];
            /**
             * Authors Complete
             * @default true
             */
            authors_complete: boolean;
            /** Citation Count */
            citation_count: number | null;
            /**
             * Cited By In Graph
             * @default 0
             */
            cited_by_in_graph: number;
            /** Description */
            description: string | null;
            /** Doi */
            doi: string | null;
            /** Id */
            id: string;
            /**
             * Is Stub
             * @default false
             */
            is_stub: boolean;
            /** Keywords */
            keywords: string[];
            /** Language */
            language: string | null;
            metrics: components["schemas"]["GraphMetrics"];
            /** Openalex Id */
            openalex_id: string | null;
            /** Publication Date */
            publication_date: string | null;
            /**
             * References In Graph
             * @default 0
             */
            references_in_graph: number;
            /** Sources */
            sources: string[];
            /** Title */
            title: string | null;
            /** Topics */
            topics: components["schemas"]["TopicRef"][];
            /** Url */
            url: string | null;
            venue: components["schemas"]["VenueRef"] | null;
            /** Year */
            year: number | null;
        };
        /** PaperSummary */
        PaperSummary: {
            /** Arxiv Id */
            arxiv_id: string | null;
            /** Authors */
            authors: string[];
            /** Citation Count */
            citation_count: number | null;
            /**
             * Cited By In Graph
             * @default 0
             */
            cited_by_in_graph: number;
            /** Doi */
            doi: string | null;
            /** Id */
            id: string;
            /**
             * Is Stub
             * @default false
             */
            is_stub: boolean;
            /** Pagerank */
            pagerank: number | null;
            /** Title */
            title: string | null;
            /** Venue */
            venue: string | null;
            /** Year */
            year: number | null;
        };
        /** PathNode */
        PathNode: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Name */
            name: string | null;
            /** Year */
            year: number | null;
        };
        /** PathRelationship */
        PathRelationship: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Type */
            type: string;
        };
        /** PathResponse */
        PathResponse: {
            /** Explanation */
            explanation: string;
            /** Found */
            found: boolean;
            /** Length */
            length: number | null;
            /** Nodes */
            nodes: components["schemas"]["PathNode"][];
            /** Relationships */
            relationships: components["schemas"]["PathRelationship"][];
        };
        /** RankedAuthor */
        RankedAuthor: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Paper Count */
            paper_count: number | null;
            /** Score */
            score: number;
        };
        /** RankedPaper */
        RankedPaper: {
            paper: components["schemas"]["PaperSummary"];
            /** Score */
            score: number;
        };
        /** RelatedTopic */
        RelatedTopic: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Shared Papers */
            shared_papers: number;
        };
        /** SearchHit */
        SearchHit: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "paper" | "author" | "topic";
            /** Score */
            score: number;
            /** Subtitle */
            subtitle: string | null;
            /** Title */
            title: string;
        };
        /** SearchResults */
        SearchResults: {
            /** Authors */
            authors: components["schemas"]["SearchHit"][];
            /** Papers */
            papers: components["schemas"]["SearchHit"][];
            /** Query */
            query: string;
            /** Topics */
            topics: components["schemas"]["SearchHit"][];
        };
        /** SimilarPaper */
        SimilarPaper: {
            /** Explanation */
            explanation: string;
            /**
             * Method
             * @enum {string}
             */
            method: "coupling" | "cocitation" | "ppr";
            paper: components["schemas"]["PaperSummary"];
            /** Score */
            score: number;
            /** Shared */
            shared: number | null;
        };
        /** TopicDetail */
        TopicDetail: {
            /** Description */
            description: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Paper Count
             * @default 0
             */
            paper_count: number;
            /** Papers Per Year */
            papers_per_year: {
                [key: string]: number;
            };
            /** Related Topics */
            related_topics: components["schemas"]["RelatedTopic"][];
            /** Top Authors */
            top_authors: components["schemas"]["AuthorActivity"][];
            /** Top Papers */
            top_papers: components["schemas"]["PaperSummary"][];
        };
        /** TopicListItem */
        TopicListItem: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Paper Count */
            paper_count: number;
        };
        /** TopicRef */
        TopicRef: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Score */
            score: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VenueRef */
        VenueRef: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string | null;
        };
        /** YearCount */
        YearCount: {
            /** Papers */
            papers: number;
            /** Year */
            year: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    influential_api_analytics_influential_get: {
        parameters: {
            query?: {
                entity?: "paper" | "author";
                metric?: "pagerank" | "betweenness" | "in_degree" | "paper_count";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfluentialResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_analytics_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_analytics_runs_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyticsRunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_analytics_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_analytics_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphSummary"];
                };
            };
        };
    };
    papers_per_year_api_analytics_years_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YearCount"][];
                };
            };
        };
    };
    get_author_api_authors__author_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                author_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_communities_api_communities_get: {
        parameters: {
            query?: {
                scope?: "papers" | "authors";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunitySummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_community_api_communities__community_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                community_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    neighborhood_api_graph_neighborhood__paper_id__get: {
        parameters: {
            query?: {
                depth?: number;
                limit?: number;
            };
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_graph_overview_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shortest_path_api_graph_shortest_path_get: {
        parameters: {
            query: {
                source: string;
                target: string;
                /** @description Relationship types to traverse (default: CITES) */
                relationships?: ("CITES" | "WROTE" | "HAS_TOPIC" | "PUBLISHED_IN" | "HAS_KEYWORD" | "AFFILIATED_WITH" | "COLLABORATED_WITH" | "RELATED_TO")[] | null;
                max_hops?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_api_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_jobs_api_ingestion_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionJobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_api_ingestion_jobs_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestionJobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionJobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_ingestion_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionJobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_job_api_ingestion_jobs__job_id__resume_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionJobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_papers_api_papers_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                year_from?: number | null;
                year_to?: number | null;
                topic_id?: string | null;
                sort?: "year" | "pagerank" | "cited_by";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PaperSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_paper_api_papers__paper_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_citations_api_papers__paper_id__citations_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PaperSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_references_api_papers__paper_id__references_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PaperSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    related_papers_api_papers__paper_id__related_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarPaper"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    similar_papers_api_papers__paper_id__similar_get: {
        parameters: {
            query?: {
                method?: "coupling" | "cocitation";
                limit?: number;
            };
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarPaper"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResults"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_topics_api_topics_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TopicListItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_topic_api_topics__topic_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
