from __future__ import annotations

from app.ai.insights import PaperInsight
from app.schemas.common import ResponseModel


class PaperInsightResult(ResponseModel):
    paper_id: str
    insight: PaperInsight
    model: str
    generated_at: str
    # True when the paper's text (or the prompt) changed since this insight was generated.
    stale: bool = False
    # True when served from storage rather than freshly generated by this request.
    cached: bool = True
