import { type FormEvent, Fragment, useState } from "react";
import { Link } from "react-router-dom";

import { useAsk } from "../api/queries";
import type { AskResponse } from "../api/types";
import { PageHeader } from "../components/PageHeader";
import { ErrorState, Loading } from "../components/StateViews";
import { formatAuthors, paperTitle } from "../lib/format";

const EXAMPLES = [
  "How do transformers differ from recurrent models?",
  "What methods exist for detecting fraud with graph neural networks?",
  "How can retrieval improve language model answers?",
];

/** Split an answer into text and [n] markers so markers can link to their source. */
function AnswerText({ text }: { text: string }) {
  const parts = text.split(/(\[\d+\])/g);
  return (
    <p className="answer-text">
      {parts.map((part, i) => {
        const m = /^\[(\d+)\]$/.exec(part);
        return m ? (
          <a key={i} className="cite" href={`#source-${m[1]}`} aria-label={`Source ${m[1]}`}>
            [{m[1]}]
          </a>
        ) : (
          <Fragment key={i}>{part}</Fragment>
        );
      })}
    </p>
  );
}

function Answer({ data }: { data: AskResponse }) {
  const byNumber = new Map(data.sources.map((s) => [s.n, s]));
  return (
    <div className="stack">
      <section className="card card-pad" aria-labelledby="answer-heading">
        <h2 id="answer-heading">Answer</h2>
        {/* Model output is untrusted: plain text only; markers become same-page links. */}
        <AnswerText text={data.answer} />
        {!data.answerable && (
          <p className="note small">The retrieved papers do not contain enough to answer this.</p>
        )}
        {data.answerable && !data.grounded && (
          <p className="note small">
            This answer cites no source, so treat it as unverified.
          </p>
        )}
        {data.retrieval.note && <p className="note small">{data.retrieval.note}</p>}
        <p className="small faint">
          Generated by {data.model ?? "no model"} from {data.retrieval.retrieved} retrieved
          {data.retrieval.expanded > 0 && ` and ${data.retrieval.expanded} citation-linked`} papers.
          AI output can be wrong; check claims against the sources.
        </p>
      </section>

      {data.sources.length > 0 && (
        <section className="card card-pad" aria-labelledby="sources-heading">
          <h2 id="sources-heading">Sources</h2>
          <ol className="sources">
            {data.sources.map((s) => (
              <li key={s.n} id={`source-${s.n}`} className="source">
                <span className="source-n">[{s.n}]</span>
                <div>
                  <Link to={`/papers/${encodeURIComponent(s.paper.id)}`}>{paperTitle(s.paper.title)}</Link>
                  <div className="row-meta">
                    {formatAuthors(s.paper.authors)}
                    {s.paper.year != null && <> · {s.paper.year}</>}
                  </div>
                  <div className="chips" style={{ margin: "6px 0" }}>
                    <span className="chip">
                      {s.role === "retrieved" ? "Matched your question" : `Cited by or citing ${s.links_to_retrieved} matched`}
                    </span>
                    <span className={s.cited ? "chip chip-accent" : "chip"}>
                      {s.cited ? "Cited in answer" : "Not cited"}
                    </span>
                  </div>
                  {s.excerpt && <p className="small muted source-excerpt">{s.excerpt}</p>}
                </div>
              </li>
            ))}
          </ol>
        </section>
      )}

      {data.relations.length > 0 && (
        <section className="card card-pad" aria-labelledby="links-heading">
          <h2 id="links-heading">How the sources connect</h2>
          <ul className="plain">
            {data.relations.map((r) => (
              <li key={`${r.source}-${r.target}`}>
                <a href={`#source-${r.source}`}>[{r.source}]</a> cites <a href={`#source-${r.target}`}>[{r.target}]</a>
                <span className="muted small">
                  {" "}
                  — {paperTitle(byNumber.get(r.source)?.paper.title)} → {paperTitle(byNumber.get(r.target)?.paper.title)}
                </span>
              </li>
            ))}
          </ul>
        </section>
      )}
    </div>
  );
}

export function AskPage() {
  const [question, setQuestion] = useState("");
  const [useGraph, setUseGraph] = useState(true);
  const ask = useAsk();

  const onSubmit = (e: FormEvent) => {
    e.preventDefault();
    const text = question.trim();
    if (text.length >= 3) ask.mutate({ question: text, expand: useGraph ? 3 : 0 });
  };

  return (
    <div className="stack">
      <PageHeader
        title="Ask the literature"
        subtitle="Answers use only papers in this graph and cite each claim, so you can check it."
      />
      <form className="card filters" onSubmit={onSubmit}>
        <label className="field" style={{ flex: 1, minWidth: 260 }}>
          Question
          <textarea
            rows={2}
            maxLength={500}
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
            placeholder="e.g. How can retrieval improve language model answers?"
          />
        </label>
        <label className="check">
          <input type="checkbox" checked={useGraph} onChange={(e) => setUseGraph(e.target.checked)} />
          Also use papers linked by citations
        </label>
        <button type="submit" className="btn btn-primary" disabled={ask.isPending || question.trim().length < 3}>
          {ask.isPending ? "Thinking…" : "Ask"}
        </button>
      </form>

      {!ask.data && !ask.isPending && !ask.isError && (
        <div className="card card-pad">
          <p className="muted">Try one of these:</p>
          <div className="chips">
            {EXAMPLES.map((e) => (
              <button key={e} type="button" className="chip chip-button" onClick={() => setQuestion(e)}>
                {e}
              </button>
            ))}
          </div>
        </div>
      )}
      {ask.isPending && <Loading label="Searching the graph and writing an answer" />}
      {ask.isError && <ErrorState error={ask.error} />}
      {ask.data && <Answer data={ask.data} />}
    </div>
  );
}
